name: Compile Resume
on:
  push:
    branches:
      - "main"
    paths:
      - "resume.tex"
      - ".github/workflows/**"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          latexmk_use_xelatex: true
              
      - uses: actions/upload-artifact@v2
        with:
          name: Resume_${{ steps.date.outputs.date }}
          path: resume.pdf
